////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2025 OVITO GmbH, Germany
//
//  This file is part of OVITO (Open Visualization Tool).
//
//  OVITO is free software; you can redistribute it and/or modify it either under the
//  terms of the GNU General Public License version 3 as published by the Free Software
//  Foundation (the "GPL") or, at your option, under the terms of the MIT License.
//  If you do not alter this notice, a recipient may use your version of this
//  file under either the GPL or the MIT License.
//
//  You should have received a copy of the GPL along with this program in a
//  file LICENSE.GPL.txt.  You should have received a copy of the MIT License along
//  with this program in a file LICENSE.MIT.txt
//
//  This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND,
//  either express or implied. See the GPL or the MIT License for the specific language
//  governing rights and limitations.
//
////////////////////////////////////////////////////////////////////////////////////////

#pragma once


#include <ovito/core/Core.h>
#include <ovito/core/oo/OvitoObject.h>

namespace Ovito {

/**
 * Abstract frame buffer a RenderingJob renders into (e.g. an OpenGL frame buffer or an ANARI frame object).
 */
class OVITO_CORE_EXPORT RenderBuffer : public OvitoObject
{
	OVITO_CLASS(RenderBuffer)

public:

    /// Constructor.
    void initializeObject(const QSize& size) {
		OvitoObject::initializeObject();
		const_cast<QSize&>(_size) = size;
	}

	/// Returns the physical size of the buffer in pixels.
	const QSize& size() const { return _size; }

	/// Records an issue message, which will be displayed to the user during or after the current rendering pass.
	void reportIssue(const QString& msg);

	/// Resets the list of issue messages. This should be called before starting a new rendering pass.
	void resetIssues() { _issueMessages.clear(); }

	/// Returns the list of issue messages generated by the renderer during the last render pass, which should be displayed in the UI.
	const QStringList& renderingIssues() const { return _issueMessages; }

private:

	/// The physical size of the buffer in pixels.
	const QSize _size;

	/// Issue messages generated by the renderer during the last render pass, which should be displayed in the UI.
	QStringList _issueMessages;
};

}	// End of namespace
