image: registry.gitlab.com/stuko/ovito/linux_build:latest

test_linux:
   stage: build
   tags:
      - linux
   script:
      - mkdir build
      - cd build

      # Configure the build.
      # For the list of required dependencies, see doc/manual/development/build_linux.rst.
      - cmake
           -DCMAKE_BUILD_TYPE=Debug
           -DOVITO_BUILD_DOCUMENTATION=ON
           -DOVITO_BUILD_PLUGIN_VULKAN=OFF
           -DCMAKE_INSTALL_PREFIX=../install
           ..
      
      # Build the application:
      - make -j2 install
      
      # Test if the application can be started (at least in headless mode):
      - ../install/bin/ovito --nogui

      # Run any tests the CMake script may define:
      - ctest --output-on-failure
