////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2024 OVITO GmbH, Germany
//
//  This file is part of OVITO (Open Visualization Tool).
//
//  OVITO is free software; you can redistribute it and/or modify it either under the
//  terms of the GNU General Public License version 3 as published by the Free Software
//  Foundation (the "GPL") or, at your option, under the terms of the MIT License.
//  If you do not alter this notice, a recipient may use your version of this
//  file under either the GPL or the MIT License.
//
//  You should have received a copy of the GPL along with this program in a
//  file LICENSE.GPL.txt.  You should have received a copy of the MIT License along
//  with this program in a file LICENSE.MIT.txt
//
//  This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND,
//  either express or implied. See the GPL or the MIT License for the specific language
//  governing rights and limitations.
//
////////////////////////////////////////////////////////////////////////////////////////

#pragma once


#include <ovito/core/Core.h>
#include <ovito/core/oo/OORef.h>

namespace Ovito {

/**
 * \brief Manages running asynchronous tasks and a queue of pending work items that need to be executed in the main thread.
 */
class OVITO_CORE_EXPORT TaskManager : public QObject
{
    Q_OBJECT

public:

    /// Constructor.
    TaskManager(UserInterface* ui);

#ifdef OVITO_DEBUG
    /// Destructor.
    virtual ~TaskManager();
#endif

    /// \brief Registers a future with the TaskManager, which will subsequently track the progress of the associated operation.
    /// \param future The Future whose shared state should be registered.
    /// \note This function is thread-safe.
    void registerFuture(const FutureBase& future);

    /// \brief Registers a promise with the TaskManager, which will subsequently track the progress of the associated operation.
    /// \param promise The Promise whose shared state should be registered.
    /// \note This function is thread-safe.
    void registerPromise(const PromiseBase& promise);

    /// Registers a Task with the TaskManager, which will subsequently track the progress of the associated operation.
    /// \note This function is thread-safe.
    void registerTask(Task& task);

    /// Returns whether printing of task status messages to the console is currently enabled.
    bool consoleLoggingEnabled() const { return _consoleLoggingEnabled; }

    /// Enables or disables printing of task status messages to the console for this task manager.
    void setConsoleLoggingEnabled(bool enabled);

    /// Indicates whether the session is in the processing of shutting down.
    bool isShuttingDown() const { return _isShuttingDown; }

#ifdef OVITO_USE_SYCL
    /// Returns the main SYCL out-of-order queue to which work can be submitted.
    SYCL_NS::queue& syclQueue() { return _syclQueue; }
#endif

    /// Cancels all running tasks and waits for them to finish.
    void shutdown();

    /// Executes the given function at some later time unless the given object is destroyed in the meantime or the task manager is shut down.
    void submitWork(const OvitoObject* contextObject, fu2::unique_function<void() noexcept> function, bool isScriptingContext);

    /// Calls the given function object for each registered task.
    template<typename Function>
    void visitRegisteredTasks(Function&& func) {
        std::unique_lock<std::mutex> lock{_mutex};
        for(const std::weak_ptr<Task>& weakPtr : _registeredTasks) {
            if(auto task = weakPtr.lock())
                func(task);
        }
    }

public Q_SLOTS:

    /// Executes pending work items waiting in the deferred execution queue.
    void executePendingWork() {
        std::unique_lock<std::mutex> lock{_mutex};
        executePendingWorkLocked(lock);
    }

    /// Tells the task manager to interrupt the task it is currently waiting for.
    void requestInterruption();

Q_SIGNALS:

    /// This signal is generated by the task manager whenever a new task got registered with this task manager.
    void taskRegistered(TaskPtr task);

    /// This signal is emitted by submitWork() when the pending work queue becomes non-empty.
    void pendingWorkArrived();

private:

    /// Executes pending work items waiting in the deferred execution queue.
    void executePendingWorkLocked(std::unique_lock<std::mutex>& lock);

    /// Keeps executing pending work items until quitWorkProcessingLoop() is called or the awaited task has finished.
    void processWorkWhileWaiting(Task* waitingTask, detail::TaskReference& awaitedTask);

    /// Stops executing pending work items and makes processWorkWhileWaiting() return.
    void quitWorkProcessingLoop(bool& quitFlag);

private:

    /// The abstract user interface object this task manager belongs to.
    UserInterface* _ui;

    /// Enables printing of task status messages to the console.
    bool _consoleLoggingEnabled = false;

    /// Indicates whether the session is in the processing of shutting down.
    bool _isShuttingDown = false;

#ifdef OVITO_USE_SYCL
    /// The main SYCL out-of-order queue for work on the compute device.
    SYCL_NS::queue _syclQueue;

    /// The head of the linked list of RegisteredBufferAccess objects associated with this task manager's SYCL queue.
    RegisteredBufferAccess* _registeredBufferAccessors = nullptr;
#endif

    /// A piece of work that has been submitted for deferred execution in the main thread.
    struct Work
    {
        /// Constructor.
        template<typename Function>
        Work(OOWeakRef<const OvitoObject> obj_, Function&& function_, bool isScriptingContext_) :
            obj(std::move(obj_)), function(std::forward<Function>(function_)), isScriptingContext(isScriptingContext_) {}

        /// The context object this work is associated with.
        /// If the object is destroyed before the work is executed, the work is canceled.
        OOWeakRef<const OvitoObject> obj;

        /// The function to be executed.
        fu2::unique_function<void() noexcept> function;

        /// Indicates whether the work is being performed in a scripting context or an interactive context.
        bool isScriptingContext;
    };

    /// The queue of all pending work items that have been submitted for deferred execution in the main thread.
    std::queue<Work> _pendingWork;

    /// Used to signal the arrival of new work items in the queue.
    std::condition_variable _pendingWorkCondition;

    /// Indicates that we are currently waiting for a task to finish in processWorkWhileWaiting().
    bool _isWaitingForTask = false;

    /// Indicates that the work processing loop should be interrupted.
    bool _interruptProcessingLoop = false;

    /// The list of registered task objects.
    std::vector<std::weak_ptr<Task>> _registeredTasks;

    /// Manages thread-safe concurrent access to the work queue and task list.
    std::mutex _mutex;

    /// The current local event loop started by processWorkWhileWaiting();
    QEventLoop* _localEventLoop = nullptr;

    friend class RegisteredBufferAccess;
    friend class Task;
};

}   // End of namespace
